name: towerify
recipe: laravel
config:
  php: '8.3'
  database: mysql:8.0
  config:
    database: /dev/null
  webroot: ./public
services:
  node:
    type: node:14
    build:
      - npm install
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
tooling:
  node:
    service: node
  npm:
    service: node
