x-common: &common
  image: towerify:latest
  depends_on:
    db:
      condition: service_healthy
  restart: unless-stopped
  env_file:
    - .env
  volumes:
    - .:/var/www/html

services:
  app:
    <<: *common
    build:
      context: .
      dockerfile: ./towerify/Dockerfile
    ports:
      - "8178:80"

  scheduler:
    <<: *common
    environment:
      - CONTAINER_ROLE=scheduler

  queue:
    <<: *common
    environment:
      - CONTAINER_ROLE=queue

  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=towerify
      - MYSQL_USER=towerify
      - MYSQL_PASSWORD=towerify
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "towerify", "-ptowerify"]
      interval: 30s
      timeout: 5s
      retries: 5