name: performa
type: static
config:
  dockerfile: ./towerify/Dockerfile
  stackfile: ./towerify/stack.yaml
  envs:
    zdhi-8skn-fu6v:
      domain: zdhi-8skn-fu6v.cywise.io
    v29m-tcdr-kqx2:
      domain: v29m-tcdr-kqx2.cywise.io
    js5f-4t7e-5er8:
      domain: js5f-4t7e-5er8.cywise.io
    hf5y-rhal-8tr4:
      domain: hf5y-rhal-8tr4.cywise.io
    ka8u-e1fs-3qmh:
      domain: ka8u-e1fs-3qmh.cywise.io
