name: OSSEC Powershell Unit Tests

on:
 push:
   paths:
     - resources/ossec/powershell/**
 pull_request:
   paths:
     - resources/ossec/powershell/**

jobs:
  test-pwsh:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Run Pester tests (pwsh)
      working-directory: ./resources/ossec/powershell
      run: |
        Write-host PowerShell $PSVersionTable.PSVersion under $PSVersionTable.OS
        Set-PSRepository psgallery -InstallationPolicy trusted
        Install-Module -Name Pester -confirm:$false -Force -SkipPublisherCheck
        ./RunTests.ps1
      shell: pwsh
