name: tests

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      matrix:
        php: [ '8.3' ]
        laravel: [ '11.20' ]
    name: PHP ${{ matrix.php }} Laravel ${{ matrix.laravel }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Installing PHP
        uses: shivammathur/setup-php@main
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, json, sqlite3
          tools: composer:v2
      - name: Lock Laravel Version
        run: composer require "laravel/framework:${{ matrix.laravel }}.*" --no-update -v
      - name: Composer Install
        run: composer install --prefer-dist --no-progress --no-interaction
        env:
          DB_CONNECTION: sqlite
          DB_HOST: 127.0.0.1
          DB_DATABASE: ":memory:"
          DB_PORT: 3000
          DB_USERNAME: root
          DB_PASSWORD: ""
      - name: Start MySQL
        run: sudo /etc/init.d/mysql start
      - name: Create TWR database
        run: mysql --host 127.0.0.1 --port 3306 -uroot -e "CREATE DATABASE tw_testdb DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
      - name: Check TWR database exists
        run: mysql --host 127.0.0.1 --port 3306 -uroot -e "SHOW DATABASES LIKE 'tw_testdb';"
      - name: Create TWR database user
        run: mysql --host 127.0.0.1 --port 3306 -uroot -e "CREATE USER 'tw_testuser'@'localhost' IDENTIFIED BY 'z0rglub';"
      - name: Grant TWR database user privileges
        run: mysql --host 127.0.0.1 --port 3306 -uroot -e "GRANT ALL ON tw_testdb.* TO 'tw_testuser'@'localhost';"
      - name: Create AM database
        run: mysql --host 127.0.0.1 --port 3306 -uroot -e "CREATE DATABASE tw_testdb_am DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
      - name: Check AM database exists
        run: mysql --host 127.0.0.1 --port 3306 -uroot -e "SHOW DATABASES LIKE 'tw_testdb_am';"
      - name: Create TWR database user
        run: mysql --host 127.0.0.1 --port 3306 -uroot -e "CREATE USER 'tw_testuser_am'@'localhost' IDENTIFIED BY 'tapa2$';"
      - name: Grant TWR database user privileges
        run: mysql --host 127.0.0.1 --port 3306 -uroot -e "GRANT ALL ON tw_testdb_am.* TO 'tw_testuser_am'@'localhost';"
      - name: Run Tests
        run: php vendor/bin/phpunit --testdox
        env:
          DB_PORT: 3306
          DB_PORT_AM: 3306